version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - React
      - build:
          requires:
            - React

jobs:
  React:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run: npm install
      - run: npm install --save @types/react-router-dom

  build:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run: npm install
      - run: npm install --save @types/react-router-dom
      - run: npm run build
